### ISSUE TITLE
Name the screenshot folder after the test

### ISSUE THREAD

**Issue by ondrej-mach** [redhat-qe-security/SC-tests#20]
When testing GUI, a folder for screenshots is created. This folder has the name of current timestamp. Instead, it would be better to have it named after the test. Pytest framework allows reading the name from a [fixture](https://stackoverflow.com/questions/17726954/py-test-how-to-get-the-current-tests-name-from-the-setup-method).
This feature firstly has to be implemented in [SCAutolib](https://github.com/redhat-qe-security/SCAutolib/issues/120).

**Comment by GeorgePantelakis** [comment]
Feature implemented in [SCAutolib PR#135](https://github.com/redhat-qe-security/SCAutolib/pull/135). Closing issue.
